[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6.0"
actix-web-actors = "4"
simple_logger = "2.1.0"
log = "0.4.14"
shared = { path = "../shared" }